#cloud-config
hostname: dev01
fqdn: dev01.internal
manage_etc_hosts: true
users:
  - default
  - name: rory
    ssh-authorized-keys:
      - ssh-rsa
      - ssh-rsa 
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    passwd: D3l1l@h2020
package_upgrade: true
package_reboot_if_required: true
locale: en_GB.UTF-8
timezone: Europe/London
packages:
  - nano
  - git
  - 

